---
- name: Install Cargo (The Rust package manager)
  apt: name=cargo state=present
  register: cargo_installed
- name: Install ripgrep (a line-oriented search tool)
  command: cargo install ripgrep
  when: cargo_installed is success
