---
- name: Install ProxyChains (TCP/DNS through proxy server)
  apt: name=proxychains state=present
- name: ProxyChains - Configure proxies
  shell: "/ansible/scripts/get_proxy_list.sh | tee -a /etc/proxychains.conf"
- name: ProxyChains - Sets tcp_read_time_out
  lineinfile:
    dest: /etc/proxychains.conf
    regexp: '^tcp_read_time_out'
    line: 'tcp_read_time_out 30000'
- name: ProxyChains - Sets tcp_connect_time_out
  lineinfile:
    dest: /etc/proxychains.conf
    regexp: '^tcp_connect_time_out'
    line: 'tcp_connect_time_out 30000'
