- hosts: localhost
  environment:
    ANSIBLE_CONFIG: '/ansible/ansible.cfg'
    CARGO_INSTALL_ROOT: '/usr/local'
    GOPATH: '/usr/local'
  tasks:
    - name: Install bc (an arbitrary precision calculator)
      apt: name=bc state=present
    - name: Install curl (CLI for transferring data)
      apt: name=curl state=present
    - name: Install wget (CLI for non-interactive downloads)
      apt: name=wget state=present
    - name: Install Vim (a terminal text editor)
      apt: name=vim state=present
    - name: Install JQ (CLI JSON processor)
      apt: name=jq state=present
    - import_tasks: tasks/install_proxychains.yml
    - import_tasks: tasks/install_pup.yml
    - import_tasks: tasks/install_rargs.yml
    - import_tasks: tasks/install_torsocks.yml
#   - import_tasks: tasks/dotfiles.yml
#   - import_tasks: tasks/gitconfig.yml
