- hosts: localhost
  tasks:
    - name: Install curl (CLI for transferring data)
      apt: name=curl state=present
    - name: Install wget (CLI for non-interactive downloads)
      apt: name=wget state=present
    - name: Install Vim (a terminal text editor)
      apt: name=vim state=present
    - name: Install ProxyChains (TCP/DNS through proxy server)
      apt: name=proxychains state=present
    - name: Install torsocks (library to torify applications)
      apt: name=torsocks state=present
