- hosts: localhost
  tasks:
    - name: Install curl (CLI for transferring data)
      apt: name=curl state=present
    - name: Install wget (CLI for non-interactive downloads)
      apt: name=wget state=present
    - name: Install Vim (a terminal text editor)
      apt: name=vim state=present
    - name: Install JQ (CLI JSON processor)
      apt: name=jq state=present
    - import_tasks: tasks/install_proxychains.yml
    - import_tasks: tasks/install_torsocks.yml
#   - import_tasks: tasks/dotfiles.yml
#   - import_tasks: tasks/gitconfig.yml
