- hosts: localhost
  environment:
    ANSIBLE_CONFIG: '/ansible/ansible.cfg'
    CARGO_INSTALL_ROOT: '/usr/local'
    GOPATH: '/usr/local'
    RUSTFLAGS: '-C prefer-dynamic'
  tasks:
    - name: Install bc (an arbitrary precision calculator)
      apt: name=bc state=present
    - name: Install curl (CLI for transferring data)
      apt: name=curl state=present
    - name: Install wget (CLI for non-interactive downloads)
      apt: name=wget state=present
    - name: Install Vim (a terminal text editor)
      apt: name=vim state=present
    - name: Install JQ (CLI JSON processor)
      apt: name=jq state=present
    - name: Install strace (debugging utility)
      apt: name=strace state=present
    - import_tasks: tasks/configure_git.yml
    - import_tasks: tasks/configure_sudo.yml
    - import_tasks: tasks/install_git.yml
    - import_tasks: tasks/install_proxychains.yml
    - import_tasks: tasks/install_pup.yml
    - import_tasks: tasks/install_rg.yml
    - import_tasks: tasks/install_tor.yml
#   - import_tasks: tasks/dotfiles.yml
#   - import_tasks: tasks/install_nodejs.yml
#   - import_tasks: tasks/install_rargs.yml
    - name: Apt - Remove unused dependency packages and cleans the local repository
      apt: autoclean=yes autoremove=yes
    - name: Apt - Removes all packages from the package cache
      command: apt-get clean warn=False
